plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.3.0+'
}

group = 'org.jquic'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    mavenLocal()
}

tasks.register('runShadowJar', JavaExec) {
    group = 'application'
    description = 'Runs the shadow fat JAR file.'

    // Automatically wait for shadowJar to build before running
    dependsOn tasks.named('shadowJar')

    // Dynamically references the exact file location of the shadow archive
    classpath = files(tasks.named('shadowJar').flatMap { it.archiveFile })

    // Forces the execution environment to be the project root directory
    workingDir = project.projectDir

    // Pass your VM options/arguments here
    jvmArgs = [
            '--add-opens', 'java.base/sun.nio.ch=ALL-UNNAMED',
            '--add-opens', 'java.base/java.io=ALL-UNNAMED',
            '--enable-native-access=ALL-UNNAMED'
    ]
}

dependencies {
    implementation 'ch.qos.logback:logback-classic:1.5.38'
    implementation project(':http3')

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

shadowJar {
    manifest {
        attributes(
                'Main-Class': 'org.jquic.Main' // Replace with your main class
        )
    }
}

test {
    useJUnitPlatform()
}