plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.3.0+'
}

group = 'org.jquic'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation 'ch.qos.logback:logback-classic:1.5.38'
    implementation('org.jquic:http3:1.0-SNAPSHOT')

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

shadowJar {
    manifest {
        attributes(
                'Main-Class': 'org.jquic.Main' // Replace with your main class
        )
    }
}

test {
    useJUnitPlatform()
}