# QUIC Server Properties
# The UDP port the QUIC server will listen on.
quic.port=4433
# Number of selector threads for handling I/O operations.
quic.selector_count=4
# Number of worker threads for processing application-level logic.
quic.worker_count=4

# SelectorThread Settings
# Capacity of the queue for outbound application data.
quic.outbound_app_queue_size=1000
# Capacity of the queue for incoming handshake packets.
quic.handshake_queue_cap=1000
# Maximum number of packets to receive in a single batch.
quic.max_receive_batch=64
# Maximum number of packets to send in a single batch.
quic.max_send_batch=128
# Interval in milliseconds for checking connection timeouts.
quic.timeout_check_interval_ms=1000

# Connection Settings
# Default idle timeout for a connection in milliseconds.
quic.default_idle_timeout_ms=30000

# InitialStreamLimits
# Initial maximum number of bidirectional streams the server is willing to accept.
quic.initial_max_bidi=128
# Initial maximum number of unidirectional streams the server is willing to accept.
quic.initial_max_uni=128
# Initial flow control limit for unidirectional streams.
quic.initial_max_stream_data_uni=1048576
# Initial flow control limit for bidirectional streams initiated by the local endpoint.
quic.initial_max_stream_data_bidi_local=1048576
# Initial flow control limit for bidirectional streams initiated by the remote endpoint.
quic.initial_max_stream_data_bidi_remote=1048576
# Initial connection-level flow control limit.
quic.initial_max_data=1048576
#  Size of connection ids pool
quic.connection_ids_limit=3

# TLS Keystore Settings
# Type of keystore: PKCS12 or PEM. Default is PKCS12.
quic.keystore_type=PKCS12
# Path to the PKCS12 keystore file (used if quic.keystore_type=PKCS12).
quic.keystore_path=server.p12
# Password for the keystore (used if quic.keystore_type=PKCS12).
quic.keystore_password=changeit
# Alias of the private key entry in the keystore (used if quic.keystore_type=PKCS12).
quic.key_alias=server-alias
# Path to the certificate file in PEM format (used if quic.keystore_type=PEM).
quic.cert_path=server.crt
# Path to the unencrypted private key file in PEM format (used if quic.keystore_type=PEM).
quic.key_path=server.key

# Bootstrap HTTP Server Settings
# The TCP port for the bootstrap server.
quic.bootstrap.port=443

# Monitoring Handler Settings
# Base directory for monitoring HTML files.
quic.monitoring.base_dir=/home/fedoresko

# Is V2 preferred to V1 protocol version
quic.prefer_v2=true