plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.3.0+'
}

group = 'org.fmalyshev'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(23)
    }
}

dependencies {
    implementation 'org.jspecify:jspecify:1.0.0'
    // Conscrypt for TLS 1.3 and modern crypto
    implementation 'org.conscrypt:conscrypt-openjdk-uber:2.5.2'

    // Slf4j API and Logback implementation
    implementation 'org.slf4j:slf4j-api:2.0.9'
    implementation 'ch.qos.logback:logback-classic:1.4.11'
    implementation 'org.jctools:jctools-core:4.0.5'
    implementation 'commons-codec:commons-codec:1.22.0'
    implementation 'tech.kwik:qpack:2.1'

        // Testing dependencies
    // JUnit 6 BOM handles all version management for JUnit libraries automatically
    testImplementation platform('org.junit:junit-bom:6.1.2')

    // JUnit dependencies (versions omitted because they are managed by the BOM)
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'

    // Latest Mockito core with full Java 25 byte-code compatibility
    testImplementation 'org.mockito:mockito-core:5.23.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.23.0'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

shadowJar {
    manifest {
        attributes(
                'Main-Class': 'org.fmalyshev.Main' // Replace with your main class
        )
    }
}

test {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += ["-h", file("src/main/c").absolutePath]
    options.compilerArgs += ["--release", "22"]
}