// Generated by jextract

package org.jquic.boringssl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct env_md_ctx_st {
 *     union {
 *         uint8_t md_data[208];
 *         uint64_t alignment;
 *     };
 *     const EVP_MD *digest;
 *     EVP_PKEY_CTX *pctx;
 *     const struct evp_md_pctx_ops *pctx_ops;
 * }
 * }
 */
public class env_md_ctx_st {

    env_md_ctx_st() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.unionLayout(
            MemoryLayout.sequenceLayout(208, digest_h.C_CHAR).withName("md_data"),
            digest_h.C_LONG_LONG.withName("alignment")
        ).withName("$anon$300:3"),
        digest_h.C_POINTER.withName("digest"),
        digest_h.C_POINTER.withName("pctx"),
        digest_h.C_POINTER.withName("pctx_ops")
    ).withName("env_md_ctx_st");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout md_data$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("$anon$300:3"), groupElement("md_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t md_data[208]
     * }
     */
    public static final SequenceLayout md_data$layout() {
        return md_data$LAYOUT;
    }

    private static final long md_data$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$300:3"), groupElement("md_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t md_data[208]
     * }
     */
    public static final long md_data$offset() {
        return md_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t md_data[208]
     * }
     */
    public static MemorySegment md_data(MemorySegment struct) {
        return struct.asSlice(md_data$OFFSET, md_data$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t md_data[208]
     * }
     */
    public static void md_data(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, md_data$OFFSET, md_data$LAYOUT.byteSize());
    }

    private static long[] md_data$DIMS = { 208 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t md_data[208]
     * }
     */
    public static long[] md_data$dimensions() {
        return md_data$DIMS;
    }
    private static final VarHandle md_data$ELEM_HANDLE = md_data$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t md_data[208]
     * }
     */
    public static byte md_data(MemorySegment struct, long index0) {
        return (byte)md_data$ELEM_HANDLE.get(struct, md_data$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t md_data[208]
     * }
     */
    public static void md_data(MemorySegment struct, long index0, byte fieldValue) {
        md_data$ELEM_HANDLE.set(struct, md_data$OFFSET, index0, fieldValue);
    }

    private static final OfLong alignment$LAYOUT = (OfLong)$LAYOUT.select(groupElement("$anon$300:3"), groupElement("alignment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t alignment
     * }
     */
    public static final OfLong alignment$layout() {
        return alignment$LAYOUT;
    }

    private static final long alignment$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$300:3"), groupElement("alignment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t alignment
     * }
     */
    public static final long alignment$offset() {
        return alignment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t alignment
     * }
     */
    public static long alignment(MemorySegment struct) {
        return struct.get(alignment$LAYOUT, alignment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t alignment
     * }
     */
    public static void alignment(MemorySegment struct, long fieldValue) {
        struct.set(alignment$LAYOUT, alignment$OFFSET, fieldValue);
    }

    private static final AddressLayout digest$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("digest"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const EVP_MD *digest
     * }
     */
    public static final AddressLayout digest$layout() {
        return digest$LAYOUT;
    }

    private static final long digest$OFFSET = $LAYOUT.byteOffset(groupElement("digest"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const EVP_MD *digest
     * }
     */
    public static final long digest$offset() {
        return digest$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const EVP_MD *digest
     * }
     */
    public static MemorySegment digest(MemorySegment struct) {
        return struct.get(digest$LAYOUT, digest$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const EVP_MD *digest
     * }
     */
    public static void digest(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(digest$LAYOUT, digest$OFFSET, fieldValue);
    }

    private static final AddressLayout pctx$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pctx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * EVP_PKEY_CTX *pctx
     * }
     */
    public static final AddressLayout pctx$layout() {
        return pctx$LAYOUT;
    }

    private static final long pctx$OFFSET = $LAYOUT.byteOffset(groupElement("pctx"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * EVP_PKEY_CTX *pctx
     * }
     */
    public static final long pctx$offset() {
        return pctx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * EVP_PKEY_CTX *pctx
     * }
     */
    public static MemorySegment pctx(MemorySegment struct) {
        return struct.get(pctx$LAYOUT, pctx$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * EVP_PKEY_CTX *pctx
     * }
     */
    public static void pctx(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pctx$LAYOUT, pctx$OFFSET, fieldValue);
    }

    private static final AddressLayout pctx_ops$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pctx_ops"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct evp_md_pctx_ops *pctx_ops
     * }
     */
    public static final AddressLayout pctx_ops$layout() {
        return pctx_ops$LAYOUT;
    }

    private static final long pctx_ops$OFFSET = $LAYOUT.byteOffset(groupElement("pctx_ops"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct evp_md_pctx_ops *pctx_ops
     * }
     */
    public static final long pctx_ops$offset() {
        return pctx_ops$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct evp_md_pctx_ops *pctx_ops
     * }
     */
    public static MemorySegment pctx_ops(MemorySegment struct) {
        return struct.get(pctx_ops$LAYOUT, pctx_ops$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct evp_md_pctx_ops *pctx_ops
     * }
     */
    public static void pctx_ops(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pctx_ops$LAYOUT, pctx_ops$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

