/*
 * Copyright 2026 Fedor Malyshev
 *
 * Licensed under the Apache License, Version 2.0 (the "License") ;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by jextract

package org.jquic.boringssl;

import org.jquic.quic.linux.NativeUtil;

import java.io.IOException;
import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.Arrays;
import java.util.stream.Collectors;

public class err_h {
    public static final ValueLayout.OfByte C_CHAR =(ValueLayout.OfByte)Linker.nativeLinker().canonicalLayouts().get("char");
    public static final ValueLayout.OfInt C_INT = (ValueLayout.OfInt) Linker.nativeLinker().canonicalLayouts().get("int");
    public static final ValueLayout.OfLong C_LONG_LONG = (ValueLayout.OfLong) Linker.nativeLinker().canonicalLayouts().get("long long");
    public static final AddressLayout C_POINTER = ((AddressLayout) Linker.nativeLinker().canonicalLayouts().get("void*"))
            .withTargetLayout(MemoryLayout.sequenceLayout(java.lang.Long.MAX_VALUE, C_CHAR));

    static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

    static void traceDowncall(String name, Object... args) {
        String traceArgs = Arrays.stream(args)
                .map(Object::toString)
                .collect(Collectors.joining(", "));
        System.out.printf("%s(%s)\n", name, traceArgs);
    }

    static {
        try {
            NativeUtil.loadLib("libcrypto");
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup();

    private static class ERR_get_error {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            err_h.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("ERR_get_error");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * uint32_t ERR_get_error()
     * }
     */
    public static int ERR_get_error() {
        var mh$ = ERR_get_error.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ERR_get_error");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ERR_error_string_n {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            err_h.C_POINTER,
            err_h.C_INT,
            err_h.C_POINTER,
            err_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("ERR_error_string_n");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * char *ERR_error_string_n(uint32_t packed_error, char *buf, size_t len)
     * }
     */
    public static MemorySegment ERR_error_string_n(int packed_error, MemorySegment buf, long len) {
        var mh$ = ERR_error_string_n.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ERR_error_string_n", packed_error, buf, len);
            }
            return (MemorySegment)mh$.invokeExact(packed_error, buf, len);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

