// Generated by jextract

package org.jquic.boringssl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct evp_cipher_info_st {
 *     const EVP_CIPHER *cipher;
 *     unsigned char iv[16];
 * } EVP_CIPHER_INFO
 * }
 */
public class EVP_CIPHER_INFO extends evp_cipher_info_st {

    EVP_CIPHER_INFO() {
        // Should not be called directly
    }
}

