// Generated by jextract

package org.jquic.boringssl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * union evp_aead_ctx_st_state {
 *     uint8_t opaque[560];
 *     uint64_t alignment;
 * }
 * }
 */
public class evp_aead_ctx_st_state {

    evp_aead_ctx_st_state() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
        MemoryLayout.sequenceLayout(560, evp_h.C_CHAR).withName("opaque"),
        evp_h.C_LONG_LONG.withName("alignment")
    ).withName("evp_aead_ctx_st_state");

    /**
     * The layout of this union
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout opaque$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("opaque"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t opaque[560]
     * }
     */
    public static final SequenceLayout opaque$layout() {
        return opaque$LAYOUT;
    }

    private static final long opaque$OFFSET = $LAYOUT.byteOffset(groupElement("opaque"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t opaque[560]
     * }
     */
    public static final long opaque$offset() {
        return opaque$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t opaque[560]
     * }
     */
    public static MemorySegment opaque(MemorySegment union) {
        return union.asSlice(opaque$OFFSET, opaque$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t opaque[560]
     * }
     */
    public static void opaque(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, opaque$OFFSET, opaque$LAYOUT.byteSize());
    }

    private static long[] opaque$DIMS = { 560 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t opaque[560]
     * }
     */
    public static long[] opaque$dimensions() {
        return opaque$DIMS;
    }
    private static final VarHandle opaque$ELEM_HANDLE = opaque$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t opaque[560]
     * }
     */
    public static byte opaque(MemorySegment union, long index0) {
        return (byte)opaque$ELEM_HANDLE.get(union, opaque$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t opaque[560]
     * }
     */
    public static void opaque(MemorySegment union, long index0, byte fieldValue) {
        opaque$ELEM_HANDLE.set(union, opaque$OFFSET, index0, fieldValue);
    }

    private static final OfLong alignment$LAYOUT = (OfLong)$LAYOUT.select(groupElement("alignment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t alignment
     * }
     */
    public static final OfLong alignment$layout() {
        return alignment$LAYOUT;
    }

    private static final long alignment$OFFSET = $LAYOUT.byteOffset(groupElement("alignment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t alignment
     * }
     */
    public static final long alignment$offset() {
        return alignment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t alignment
     * }
     */
    public static long alignment(MemorySegment union) {
        return union.get(alignment$LAYOUT, alignment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t alignment
     * }
     */
    public static void alignment(MemorySegment union, long fieldValue) {
        union.set(alignment$LAYOUT, alignment$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this union
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

