// Generated by jextract

package org.jquic.boringssl;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;

/**
 * {@snippet lang=c :
 * typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX
 * }
 */
public class EVP_CIPHER_CTX {
    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
            evp_h.C_POINTER.withName("cipher"),
            evp_h.C_POINTER.withName("app_data"),
            evp_h.C_POINTER.withName("cipher_data"),
            evp_h.C_INT.withName("key_len"),
            evp_h.C_INT.withName("encrypt"),
            evp_h.C_INT.withName("flags"),
            MemoryLayout.sequenceLayout(16, evp_h.C_CHAR).withName("oiv"),
            MemoryLayout.sequenceLayout(16, evp_h.C_CHAR).withName("iv"),
            MemoryLayout.sequenceLayout(32, evp_h.C_CHAR).withName("buf"),
            evp_h.C_INT.withName("buf_len"),
            evp_h.C_INT.withName("num"),
            evp_h.C_INT.withName("final_used"),
            MemoryLayout.sequenceLayout(32, evp_h.C_CHAR).withName("final"),
            evp_h.C_INT.withName("poisoned"),
            MemoryLayout.paddingLayout(4)
    ).withName("evp_cipher_ctx_st");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }
}

