/*
 * Copyright 2026 Fedor Malyshev
 *
 * Licensed under the Apache License, Version 2.0 (the "License") ;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by jextract

package org.jquic.boringssl;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;

/**
 * {@snippet lang=c :
 * typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX
 * }
 */
public class EVP_CIPHER_CTX {
    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
            evp_h.C_POINTER.withName("cipher"),
            evp_h.C_POINTER.withName("app_data"),
            evp_h.C_POINTER.withName("cipher_data"),
            evp_h.C_INT.withName("key_len"),
            evp_h.C_INT.withName("encrypt"),
            evp_h.C_INT.withName("flags"),
            MemoryLayout.sequenceLayout(16, evp_h.C_CHAR).withName("oiv"),
            MemoryLayout.sequenceLayout(16, evp_h.C_CHAR).withName("iv"),
            MemoryLayout.sequenceLayout(32, evp_h.C_CHAR).withName("buf"),
            evp_h.C_INT.withName("buf_len"),
            evp_h.C_INT.withName("num"),
            evp_h.C_INT.withName("final_used"),
            MemoryLayout.sequenceLayout(32, evp_h.C_CHAR).withName("final"),
            evp_h.C_INT.withName("poisoned"),
            MemoryLayout.paddingLayout(4)
    ).withName("evp_cipher_ctx_st");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }
}

