// Generated by jextract

package org.jquic.boringssl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct evp_encode_ctx_st {
 *     unsigned int data_used;
 *     uint8_t data[48];
 *     char eof_seen;
 *     char error_encountered;
 * }
 * }
 */
public class evp_encode_ctx_st {

    evp_encode_ctx_st() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        evp_h.C_INT.withName("data_used"),
        MemoryLayout.sequenceLayout(48, evp_h.C_CHAR).withName("data"),
        evp_h.C_CHAR.withName("eof_seen"),
        evp_h.C_CHAR.withName("error_encountered"),
        MemoryLayout.paddingLayout(2)
    ).withName("evp_encode_ctx_st");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt data_used$LAYOUT = (OfInt)$LAYOUT.select(groupElement("data_used"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int data_used
     * }
     */
    public static final OfInt data_used$layout() {
        return data_used$LAYOUT;
    }

    private static final long data_used$OFFSET = $LAYOUT.byteOffset(groupElement("data_used"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int data_used
     * }
     */
    public static final long data_used$offset() {
        return data_used$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int data_used
     * }
     */
    public static int data_used(MemorySegment struct) {
        return struct.get(data_used$LAYOUT, data_used$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int data_used
     * }
     */
    public static void data_used(MemorySegment struct, int fieldValue) {
        struct.set(data_used$LAYOUT, data_used$OFFSET, fieldValue);
    }

    private static final SequenceLayout data$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t data[48]
     * }
     */
    public static final SequenceLayout data$layout() {
        return data$LAYOUT;
    }

    private static final long data$OFFSET = $LAYOUT.byteOffset(groupElement("data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t data[48]
     * }
     */
    public static final long data$offset() {
        return data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t data[48]
     * }
     */
    public static MemorySegment data(MemorySegment struct) {
        return struct.asSlice(data$OFFSET, data$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t data[48]
     * }
     */
    public static void data(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, data$OFFSET, data$LAYOUT.byteSize());
    }

    private static long[] data$DIMS = { 48 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t data[48]
     * }
     */
    public static long[] data$dimensions() {
        return data$DIMS;
    }
    private static final VarHandle data$ELEM_HANDLE = data$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t data[48]
     * }
     */
    public static byte data(MemorySegment struct, long index0) {
        return (byte)data$ELEM_HANDLE.get(struct, data$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t data[48]
     * }
     */
    public static void data(MemorySegment struct, long index0, byte fieldValue) {
        data$ELEM_HANDLE.set(struct, data$OFFSET, index0, fieldValue);
    }

    private static final OfByte eof_seen$LAYOUT = (OfByte)$LAYOUT.select(groupElement("eof_seen"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char eof_seen
     * }
     */
    public static final OfByte eof_seen$layout() {
        return eof_seen$LAYOUT;
    }

    private static final long eof_seen$OFFSET = $LAYOUT.byteOffset(groupElement("eof_seen"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char eof_seen
     * }
     */
    public static final long eof_seen$offset() {
        return eof_seen$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char eof_seen
     * }
     */
    public static byte eof_seen(MemorySegment struct) {
        return struct.get(eof_seen$LAYOUT, eof_seen$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char eof_seen
     * }
     */
    public static void eof_seen(MemorySegment struct, byte fieldValue) {
        struct.set(eof_seen$LAYOUT, eof_seen$OFFSET, fieldValue);
    }

    private static final OfByte error_encountered$LAYOUT = (OfByte)$LAYOUT.select(groupElement("error_encountered"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char error_encountered
     * }
     */
    public static final OfByte error_encountered$layout() {
        return error_encountered$LAYOUT;
    }

    private static final long error_encountered$OFFSET = $LAYOUT.byteOffset(groupElement("error_encountered"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char error_encountered
     * }
     */
    public static final long error_encountered$offset() {
        return error_encountered$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char error_encountered
     * }
     */
    public static byte error_encountered(MemorySegment struct) {
        return struct.get(error_encountered$LAYOUT, error_encountered$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char error_encountered
     * }
     */
    public static void error_encountered(MemorySegment struct, byte fieldValue) {
        struct.set(error_encountered$LAYOUT, error_encountered$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

