// Generated by jextract

package org.jquic.boringssl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct evp_aead_ctx_st {
 *     const EVP_AEAD *aead;
 *     union evp_aead_ctx_st_state state;
 *     uint8_t tag_len;
 * }
 * }
 */
public class evp_aead_ctx_st {

    evp_aead_ctx_st() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        evp_h.C_POINTER.withName("aead"),
        evp_aead_ctx_st_state.layout().withName("state"),
        evp_h.C_CHAR.withName("tag_len"),
        MemoryLayout.paddingLayout(7)
    ).withName("evp_aead_ctx_st");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout aead$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("aead"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const EVP_AEAD *aead
     * }
     */
    public static final AddressLayout aead$layout() {
        return aead$LAYOUT;
    }

    private static final long aead$OFFSET = $LAYOUT.byteOffset(groupElement("aead"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const EVP_AEAD *aead
     * }
     */
    public static final long aead$offset() {
        return aead$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const EVP_AEAD *aead
     * }
     */
    public static MemorySegment aead(MemorySegment struct) {
        return struct.get(aead$LAYOUT, aead$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const EVP_AEAD *aead
     * }
     */
    public static void aead(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(aead$LAYOUT, aead$OFFSET, fieldValue);
    }

    private static final GroupLayout state$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("state"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * union evp_aead_ctx_st_state state
     * }
     */
    public static final GroupLayout state$layout() {
        return state$LAYOUT;
    }

    private static final long state$OFFSET = $LAYOUT.byteOffset(groupElement("state"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * union evp_aead_ctx_st_state state
     * }
     */
    public static final long state$offset() {
        return state$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * union evp_aead_ctx_st_state state
     * }
     */
    public static MemorySegment state(MemorySegment struct) {
        return struct.asSlice(state$OFFSET, state$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * union evp_aead_ctx_st_state state
     * }
     */
    public static void state(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, state$OFFSET, state$LAYOUT.byteSize());
    }

    private static final OfByte tag_len$LAYOUT = (OfByte)$LAYOUT.select(groupElement("tag_len"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t tag_len
     * }
     */
    public static final OfByte tag_len$layout() {
        return tag_len$LAYOUT;
    }

    private static final long tag_len$OFFSET = $LAYOUT.byteOffset(groupElement("tag_len"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t tag_len
     * }
     */
    public static final long tag_len$offset() {
        return tag_len$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t tag_len
     * }
     */
    public static byte tag_len(MemorySegment struct) {
        return struct.get(tag_len$LAYOUT, tag_len$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t tag_len
     * }
     */
    public static void tag_len(MemorySegment struct, byte fieldValue) {
        struct.set(tag_len$LAYOUT, tag_len$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

