// Generated by jextract

package org.jquic.boringssl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct evp_cipher_ctx_st {
 *     const EVP_CIPHER *cipher;
 *     void *app_data;
 *     void *cipher_data;
 *     unsigned int key_len;
 *     int encrypt;
 *     uint32_t flags;
 *     uint8_t oiv[16];
 *     uint8_t iv[16];
 *     uint8_t buf[32];
 *     int buf_len;
 *     unsigned int num;
 *     int final_used;
 *     uint8_t final[32];
 *     int poisoned;
 * }
 * }
 */
public class evp_cipher_ctx_st {

    evp_cipher_ctx_st() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        evp_h.C_POINTER.withName("cipher"),
        evp_h.C_POINTER.withName("app_data"),
        evp_h.C_POINTER.withName("cipher_data"),
        evp_h.C_INT.withName("key_len"),
        evp_h.C_INT.withName("encrypt"),
        evp_h.C_INT.withName("flags"),
        MemoryLayout.sequenceLayout(16, evp_h.C_CHAR).withName("oiv"),
        MemoryLayout.sequenceLayout(16, evp_h.C_CHAR).withName("iv"),
        MemoryLayout.sequenceLayout(32, evp_h.C_CHAR).withName("buf"),
        evp_h.C_INT.withName("buf_len"),
        evp_h.C_INT.withName("num"),
        evp_h.C_INT.withName("final_used"),
        MemoryLayout.sequenceLayout(32, evp_h.C_CHAR).withName("final"),
        evp_h.C_INT.withName("poisoned"),
        MemoryLayout.paddingLayout(4)
    ).withName("evp_cipher_ctx_st");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout cipher$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("cipher"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const EVP_CIPHER *cipher
     * }
     */
    public static final AddressLayout cipher$layout() {
        return cipher$LAYOUT;
    }

    private static final long cipher$OFFSET = $LAYOUT.byteOffset(groupElement("cipher"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const EVP_CIPHER *cipher
     * }
     */
    public static final long cipher$offset() {
        return cipher$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const EVP_CIPHER *cipher
     * }
     */
    public static MemorySegment cipher(MemorySegment struct) {
        return struct.get(cipher$LAYOUT, cipher$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const EVP_CIPHER *cipher
     * }
     */
    public static void cipher(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(cipher$LAYOUT, cipher$OFFSET, fieldValue);
    }

    private static final AddressLayout app_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("app_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *app_data
     * }
     */
    public static final AddressLayout app_data$layout() {
        return app_data$LAYOUT;
    }

    private static final long app_data$OFFSET = $LAYOUT.byteOffset(groupElement("app_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *app_data
     * }
     */
    public static final long app_data$offset() {
        return app_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *app_data
     * }
     */
    public static MemorySegment app_data(MemorySegment struct) {
        return struct.get(app_data$LAYOUT, app_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *app_data
     * }
     */
    public static void app_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(app_data$LAYOUT, app_data$OFFSET, fieldValue);
    }

    private static final AddressLayout cipher_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("cipher_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *cipher_data
     * }
     */
    public static final AddressLayout cipher_data$layout() {
        return cipher_data$LAYOUT;
    }

    private static final long cipher_data$OFFSET = $LAYOUT.byteOffset(groupElement("cipher_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *cipher_data
     * }
     */
    public static final long cipher_data$offset() {
        return cipher_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *cipher_data
     * }
     */
    public static MemorySegment cipher_data(MemorySegment struct) {
        return struct.get(cipher_data$LAYOUT, cipher_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *cipher_data
     * }
     */
    public static void cipher_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(cipher_data$LAYOUT, cipher_data$OFFSET, fieldValue);
    }

    private static final OfInt key_len$LAYOUT = (OfInt)$LAYOUT.select(groupElement("key_len"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int key_len
     * }
     */
    public static final OfInt key_len$layout() {
        return key_len$LAYOUT;
    }

    private static final long key_len$OFFSET = $LAYOUT.byteOffset(groupElement("key_len"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int key_len
     * }
     */
    public static final long key_len$offset() {
        return key_len$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int key_len
     * }
     */
    public static int key_len(MemorySegment struct) {
        return struct.get(key_len$LAYOUT, key_len$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int key_len
     * }
     */
    public static void key_len(MemorySegment struct, int fieldValue) {
        struct.set(key_len$LAYOUT, key_len$OFFSET, fieldValue);
    }

    private static final OfInt encrypt$LAYOUT = (OfInt)$LAYOUT.select(groupElement("encrypt"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int encrypt
     * }
     */
    public static final OfInt encrypt$layout() {
        return encrypt$LAYOUT;
    }

    private static final long encrypt$OFFSET = $LAYOUT.byteOffset(groupElement("encrypt"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int encrypt
     * }
     */
    public static final long encrypt$offset() {
        return encrypt$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int encrypt
     * }
     */
    public static int encrypt(MemorySegment struct) {
        return struct.get(encrypt$LAYOUT, encrypt$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int encrypt
     * }
     */
    public static void encrypt(MemorySegment struct, int fieldValue) {
        struct.set(encrypt$LAYOUT, encrypt$OFFSET, fieldValue);
    }

    private static final OfInt flags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t flags
     * }
     */
    public static final OfInt flags$layout() {
        return flags$LAYOUT;
    }

    private static final long flags$OFFSET = $LAYOUT.byteOffset(groupElement("flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t flags
     * }
     */
    public static final long flags$offset() {
        return flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t flags
     * }
     */
    public static int flags(MemorySegment struct) {
        return struct.get(flags$LAYOUT, flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t flags
     * }
     */
    public static void flags(MemorySegment struct, int fieldValue) {
        struct.set(flags$LAYOUT, flags$OFFSET, fieldValue);
    }

    private static final SequenceLayout oiv$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("oiv"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t oiv[16]
     * }
     */
    public static final SequenceLayout oiv$layout() {
        return oiv$LAYOUT;
    }

    private static final long oiv$OFFSET = $LAYOUT.byteOffset(groupElement("oiv"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t oiv[16]
     * }
     */
    public static final long oiv$offset() {
        return oiv$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t oiv[16]
     * }
     */
    public static MemorySegment oiv(MemorySegment struct) {
        return struct.asSlice(oiv$OFFSET, oiv$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t oiv[16]
     * }
     */
    public static void oiv(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, oiv$OFFSET, oiv$LAYOUT.byteSize());
    }

    private static long[] oiv$DIMS = { 16 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t oiv[16]
     * }
     */
    public static long[] oiv$dimensions() {
        return oiv$DIMS;
    }
    private static final VarHandle oiv$ELEM_HANDLE = oiv$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t oiv[16]
     * }
     */
    public static byte oiv(MemorySegment struct, long index0) {
        return (byte)oiv$ELEM_HANDLE.get(struct, oiv$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t oiv[16]
     * }
     */
    public static void oiv(MemorySegment struct, long index0, byte fieldValue) {
        oiv$ELEM_HANDLE.set(struct, oiv$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout iv$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("iv"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t iv[16]
     * }
     */
    public static final SequenceLayout iv$layout() {
        return iv$LAYOUT;
    }

    private static final long iv$OFFSET = $LAYOUT.byteOffset(groupElement("iv"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t iv[16]
     * }
     */
    public static final long iv$offset() {
        return iv$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t iv[16]
     * }
     */
    public static MemorySegment iv(MemorySegment struct) {
        return struct.asSlice(iv$OFFSET, iv$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t iv[16]
     * }
     */
    public static void iv(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, iv$OFFSET, iv$LAYOUT.byteSize());
    }

    private static long[] iv$DIMS = { 16 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t iv[16]
     * }
     */
    public static long[] iv$dimensions() {
        return iv$DIMS;
    }
    private static final VarHandle iv$ELEM_HANDLE = iv$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t iv[16]
     * }
     */
    public static byte iv(MemorySegment struct, long index0) {
        return (byte)iv$ELEM_HANDLE.get(struct, iv$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t iv[16]
     * }
     */
    public static void iv(MemorySegment struct, long index0, byte fieldValue) {
        iv$ELEM_HANDLE.set(struct, iv$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout buf$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("buf"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t buf[32]
     * }
     */
    public static final SequenceLayout buf$layout() {
        return buf$LAYOUT;
    }

    private static final long buf$OFFSET = $LAYOUT.byteOffset(groupElement("buf"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t buf[32]
     * }
     */
    public static final long buf$offset() {
        return buf$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t buf[32]
     * }
     */
    public static MemorySegment buf(MemorySegment struct) {
        return struct.asSlice(buf$OFFSET, buf$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t buf[32]
     * }
     */
    public static void buf(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, buf$OFFSET, buf$LAYOUT.byteSize());
    }

    private static long[] buf$DIMS = { 32 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t buf[32]
     * }
     */
    public static long[] buf$dimensions() {
        return buf$DIMS;
    }
    private static final VarHandle buf$ELEM_HANDLE = buf$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t buf[32]
     * }
     */
    public static byte buf(MemorySegment struct, long index0) {
        return (byte)buf$ELEM_HANDLE.get(struct, buf$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t buf[32]
     * }
     */
    public static void buf(MemorySegment struct, long index0, byte fieldValue) {
        buf$ELEM_HANDLE.set(struct, buf$OFFSET, index0, fieldValue);
    }

    private static final OfInt buf_len$LAYOUT = (OfInt)$LAYOUT.select(groupElement("buf_len"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int buf_len
     * }
     */
    public static final OfInt buf_len$layout() {
        return buf_len$LAYOUT;
    }

    private static final long buf_len$OFFSET = $LAYOUT.byteOffset(groupElement("buf_len"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int buf_len
     * }
     */
    public static final long buf_len$offset() {
        return buf_len$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int buf_len
     * }
     */
    public static int buf_len(MemorySegment struct) {
        return struct.get(buf_len$LAYOUT, buf_len$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int buf_len
     * }
     */
    public static void buf_len(MemorySegment struct, int fieldValue) {
        struct.set(buf_len$LAYOUT, buf_len$OFFSET, fieldValue);
    }

    private static final OfInt num$LAYOUT = (OfInt)$LAYOUT.select(groupElement("num"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int num
     * }
     */
    public static final OfInt num$layout() {
        return num$LAYOUT;
    }

    private static final long num$OFFSET = $LAYOUT.byteOffset(groupElement("num"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int num
     * }
     */
    public static final long num$offset() {
        return num$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int num
     * }
     */
    public static int num(MemorySegment struct) {
        return struct.get(num$LAYOUT, num$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int num
     * }
     */
    public static void num(MemorySegment struct, int fieldValue) {
        struct.set(num$LAYOUT, num$OFFSET, fieldValue);
    }

    private static final OfInt final_used$LAYOUT = (OfInt)$LAYOUT.select(groupElement("final_used"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int final_used
     * }
     */
    public static final OfInt final_used$layout() {
        return final_used$LAYOUT;
    }

    private static final long final_used$OFFSET = $LAYOUT.byteOffset(groupElement("final_used"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int final_used
     * }
     */
    public static final long final_used$offset() {
        return final_used$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int final_used
     * }
     */
    public static int final_used(MemorySegment struct) {
        return struct.get(final_used$LAYOUT, final_used$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int final_used
     * }
     */
    public static void final_used(MemorySegment struct, int fieldValue) {
        struct.set(final_used$LAYOUT, final_used$OFFSET, fieldValue);
    }

    private static final SequenceLayout final_$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("final"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t final[32]
     * }
     */
    public static final SequenceLayout final_$layout() {
        return final_$LAYOUT;
    }

    private static final long final_$OFFSET = $LAYOUT.byteOffset(groupElement("final"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t final[32]
     * }
     */
    public static final long final_$offset() {
        return final_$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t final[32]
     * }
     */
    public static MemorySegment final_(MemorySegment struct) {
        return struct.asSlice(final_$OFFSET, final_$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t final[32]
     * }
     */
    public static void final_(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, final_$OFFSET, final_$LAYOUT.byteSize());
    }

    private static long[] final_$DIMS = { 32 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t final[32]
     * }
     */
    public static long[] final_$dimensions() {
        return final_$DIMS;
    }
    private static final VarHandle final_$ELEM_HANDLE = final_$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t final[32]
     * }
     */
    public static byte final_(MemorySegment struct, long index0) {
        return (byte)final_$ELEM_HANDLE.get(struct, final_$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t final[32]
     * }
     */
    public static void final_(MemorySegment struct, long index0, byte fieldValue) {
        final_$ELEM_HANDLE.set(struct, final_$OFFSET, index0, fieldValue);
    }

    private static final OfInt poisoned$LAYOUT = (OfInt)$LAYOUT.select(groupElement("poisoned"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int poisoned
     * }
     */
    public static final OfInt poisoned$layout() {
        return poisoned$LAYOUT;
    }

    private static final long poisoned$OFFSET = $LAYOUT.byteOffset(groupElement("poisoned"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int poisoned
     * }
     */
    public static final long poisoned$offset() {
        return poisoned$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int poisoned
     * }
     */
    public static int poisoned(MemorySegment struct) {
        return struct.get(poisoned$LAYOUT, poisoned$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int poisoned
     * }
     */
    public static void poisoned(MemorySegment struct, int fieldValue) {
        struct.set(poisoned$LAYOUT, poisoned$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

