/*
 * Copyright 2026 Fedor Malyshev
 *
 * Licensed under the Apache License, Version 2.0 (the "License") ;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by jextract

package org.jquic.boringssl;

import org.jquic.quic.linux.NativeUtil;

import java.io.IOException;
import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.util.Arrays;
import java.util.stream.Collectors;

public class evp_h {
    public static final ValueLayout.OfByte C_CHAR =(ValueLayout.OfByte) Linker.nativeLinker().canonicalLayouts().get("char");
    public static final ValueLayout.OfShort C_SHORT = (ValueLayout.OfShort) Linker.nativeLinker().canonicalLayouts().get("short");
    public static final ValueLayout.OfInt C_INT = (ValueLayout.OfInt) Linker.nativeLinker().canonicalLayouts().get("int");
    public static final ValueLayout.OfLong C_LONG_LONG = (ValueLayout.OfLong) Linker.nativeLinker().canonicalLayouts().get("long long");
    public static final ValueLayout.OfFloat C_FLOAT = (ValueLayout.OfFloat) Linker.nativeLinker().canonicalLayouts().get("float");
    public static final ValueLayout.OfDouble C_DOUBLE = (ValueLayout.OfDouble) Linker.nativeLinker().canonicalLayouts().get("double");
    public static final AddressLayout C_POINTER = ((AddressLayout) Linker.nativeLinker().canonicalLayouts().get("void*"))
            .withTargetLayout(MemoryLayout.sequenceLayout(java.lang.Long.MAX_VALUE, C_CHAR));
    public static final ValueLayout C_LONG = (ValueLayout) Linker.nativeLinker().canonicalLayouts().get("long");
    public static final ValueLayout.OfDouble C_LONG_DOUBLE = (ValueLayout.OfDouble) Linker.nativeLinker().canonicalLayouts().get("double");

    static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

    static void traceDowncall(String name, Object... args) {
        String traceArgs = Arrays.stream(args)
                .map(Object::toString)
                .collect(Collectors.joining(", "));
        System.out.printf("%s(%s)\n", name, traceArgs);
    }

    static {
        try {
            NativeUtil.loadLib("libcrypto");
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup();

    private static final int EVP_AEAD_DEFAULT_TAG_LENGTH = (int)0L;
    /**
     * {@snippet lang=c :
     * #define EVP_AEAD_DEFAULT_TAG_LENGTH 0
     * }
     */
    public static int EVP_AEAD_DEFAULT_TAG_LENGTH() {
        return EVP_AEAD_DEFAULT_TAG_LENGTH;
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * void __va_start(va_list *, ...)
     * }
     */
    public static class __va_start {

    }

    /**
     * {@snippet lang=c :
     * typedef long _off_t
     * }
     */
//    public static final OfInt _off_t = evp_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef _off_t off_t
     * }
     */
//    public static final OfInt off_t = evp_h.C_LONG;

    private static class EVP_aead_aes_128_gcm {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                evp_h.C_POINTER    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("EVP_aead_aes_128_gcm");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * const EVP_AEAD *EVP_aead_aes_128_gcm()
     * }
     */
    public static MemorySegment EVP_aead_aes_128_gcm() {
        var mh$ = EVP_aead_aes_128_gcm.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("EVP_aead_aes_128_gcm");
            }
            return (MemorySegment)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }



    private static class EVP_AEAD_CTX_init {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                evp_h.C_INT,
                evp_h.C_POINTER,
                evp_h.C_POINTER,
                evp_h.C_POINTER,
                evp_h.C_LONG_LONG,
                evp_h.C_LONG_LONG,
                evp_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("EVP_AEAD_CTX_init");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }


    /**
     * {@snippet lang=c :
     * int EVP_AEAD_CTX_init(EVP_AEAD_CTX *ctx, const EVP_AEAD *aead, const uint8_t *key, size_t key_len, size_t tag_len, ENGINE *impl)
     * }
     */
    public static int EVP_AEAD_CTX_init(MemorySegment ctx, MemorySegment aead, MemorySegment key, long key_len, long tag_len, MemorySegment impl) {
        var mh$ = EVP_AEAD_CTX_init.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("EVP_AEAD_CTX_init", ctx, aead, key, key_len, tag_len, impl);
            }
            return (int)mh$.invokeExact(ctx, aead, key, key_len, tag_len, impl);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class EVP_AEAD_CTX_cleanup {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
                evp_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("EVP_AEAD_CTX_cleanup");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * void EVP_AEAD_CTX_cleanup(EVP_AEAD_CTX *ctx)
     * }
     */
    public static void EVP_AEAD_CTX_cleanup(MemorySegment ctx) {
        var mh$ = EVP_AEAD_CTX_cleanup.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("EVP_AEAD_CTX_cleanup", ctx);
            }
            mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class EVP_AEAD_CTX_seal {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                evp_h.C_INT,
                evp_h.C_POINTER,
                evp_h.C_POINTER,
                evp_h.C_POINTER,
                evp_h.C_LONG_LONG,
                evp_h.C_POINTER,
                evp_h.C_LONG_LONG,
                evp_h.C_POINTER,
                evp_h.C_LONG_LONG,
                evp_h.C_POINTER,
                evp_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("EVP_AEAD_CTX_seal");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * int EVP_AEAD_CTX_seal(const EVP_AEAD_CTX *ctx, uint8_t *out, size_t *out_len, size_t max_out_len, const uint8_t *nonce, size_t nonce_len, const uint8_t *in, size_t in_len, const uint8_t *ad, size_t ad_len)
     * }
     */
    public static int EVP_AEAD_CTX_seal(MemorySegment ctx, MemorySegment out, MemorySegment out_len, long max_out_len, MemorySegment nonce, long nonce_len, MemorySegment in, long in_len, MemorySegment ad, long ad_len) {
        var mh$ = EVP_AEAD_CTX_seal.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("EVP_AEAD_CTX_seal", ctx, out, out_len, max_out_len, nonce, nonce_len, in, in_len, ad, ad_len);
            }
            return (int)mh$.invokeExact(ctx, out, out_len, max_out_len, nonce, nonce_len, in, in_len, ad, ad_len);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class EVP_AEAD_CTX_open {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                evp_h.C_INT,
                evp_h.C_POINTER,
                evp_h.C_POINTER,
                evp_h.C_POINTER,
                evp_h.C_LONG_LONG,
                evp_h.C_POINTER,
                evp_h.C_LONG_LONG,
                evp_h.C_POINTER,
                evp_h.C_LONG_LONG,
                evp_h.C_POINTER,
                evp_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("EVP_AEAD_CTX_open");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * int EVP_AEAD_CTX_open(const EVP_AEAD_CTX *ctx, uint8_t *out, size_t *out_len, size_t max_out_len, const uint8_t *nonce, size_t nonce_len, const uint8_t *in, size_t in_len, const uint8_t *ad, size_t ad_len)
     * }
     */
    public static int EVP_AEAD_CTX_open(MemorySegment ctx, MemorySegment out, MemorySegment out_len, long max_out_len, MemorySegment nonce, long nonce_len, MemorySegment in, long in_len, MemorySegment ad, long ad_len) {
        var mh$ = EVP_AEAD_CTX_open.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("EVP_AEAD_CTX_open", ctx, out, out_len, max_out_len, nonce, nonce_len, in, in_len, ad, ad_len);
            }
            return (int)mh$.invokeExact(ctx, out, out_len, max_out_len, nonce, nonce_len, in, in_len, ad, ad_len);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }


    private static class EVP_aes_128_ecb {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                evp_h.C_POINTER    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("EVP_aes_128_ecb");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * const EVP_CIPHER *EVP_aes_128_ecb()
     * }
     */
    public static MemorySegment EVP_aes_128_ecb() {
        var mh$ = EVP_aes_128_ecb.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("EVP_aes_128_ecb");
            }
            return (MemorySegment)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class EVP_CIPHER_CTX_init {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
                evp_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("EVP_CIPHER_CTX_init");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * void EVP_CIPHER_CTX_init(EVP_CIPHER_CTX *ctx)
     * }
     */
    public static void EVP_CIPHER_CTX_init(MemorySegment ctx) {
        var mh$ = EVP_CIPHER_CTX_init.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("EVP_CIPHER_CTX_init", ctx);
            }
            mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class EVP_CIPHER_CTX_new {

    }

    private static class EVP_CIPHER_CTX_cleanup {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                evp_h.C_INT,
                evp_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("EVP_CIPHER_CTX_cleanup");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * int EVP_CIPHER_CTX_cleanup(EVP_CIPHER_CTX *ctx)
     * }
     */
    public static int EVP_CIPHER_CTX_cleanup(MemorySegment ctx) {
        var mh$ = EVP_CIPHER_CTX_cleanup.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("EVP_CIPHER_CTX_cleanup", ctx);
            }
            return (int)mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class EVP_EncryptInit_ex {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                evp_h.C_INT,
                evp_h.C_POINTER,
                evp_h.C_POINTER,
                evp_h.C_POINTER,
                evp_h.C_POINTER,
                evp_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("EVP_EncryptInit_ex");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * int EVP_EncryptInit_ex(EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, ENGINE *impl, const uint8_t *key, const uint8_t *iv)
     * }
     */
    public static int EVP_EncryptInit_ex(MemorySegment ctx, MemorySegment cipher, MemorySegment impl, MemorySegment key, MemorySegment iv) {
        var mh$ = EVP_EncryptInit_ex.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("EVP_EncryptInit_ex", ctx, cipher, impl, key, iv);
            }
            return (int)mh$.invokeExact(ctx, cipher, impl, key, iv);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class EVP_DecryptInit_ex {

    }

    private static class EVP_EncryptUpdate {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                evp_h.C_INT,
                evp_h.C_POINTER,
                evp_h.C_POINTER,
                evp_h.C_POINTER,
                evp_h.C_POINTER,
                evp_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("EVP_EncryptUpdate");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * int EVP_EncryptUpdate(EVP_CIPHER_CTX *ctx, uint8_t *out, int *out_len, const uint8_t *in, int in_len)
     * }
     */
    public static int EVP_EncryptUpdate(MemorySegment ctx, MemorySegment out, MemorySegment out_len, MemorySegment in, int in_len) {
        var mh$ = EVP_EncryptUpdate.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("EVP_EncryptUpdate", ctx, out, out_len, in, in_len);
            }
            return (int)mh$.invokeExact(ctx, out, out_len, in, in_len);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class EVP_CIPHER_CTX_set_padding {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                evp_h.C_INT,
                evp_h.C_POINTER,
                evp_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("EVP_CIPHER_CTX_set_padding");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * int EVP_CIPHER_CTX_set_padding(EVP_CIPHER_CTX *ctx, int pad)
     * }
     */
    public static int EVP_CIPHER_CTX_set_padding(MemorySegment ctx, int pad) {
        var mh$ = EVP_CIPHER_CTX_set_padding.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("EVP_CIPHER_CTX_set_padding", ctx, pad);
            }
            return (int)mh$.invokeExact(ctx, pad);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

