// Generated by jextract

package org.jquic.boringssl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct evp_encode_ctx_st EVP_ENCODE_CTX
 * }
 */
public class EVP_ENCODE_CTX extends evp_encode_ctx_st {

    EVP_ENCODE_CTX() {
        // Should not be called directly
    }
}

