// Generated by jextract

package org.jquic.boringssl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct evp_cipher_info_st {
 *     const EVP_CIPHER *cipher;
 *     unsigned char iv[16];
 * }
 * }
 */
public class evp_cipher_info_st {

    evp_cipher_info_st() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        evp_h.C_POINTER.withName("cipher"),
        MemoryLayout.sequenceLayout(16, evp_h.C_CHAR).withName("iv")
    ).withName("evp_cipher_info_st");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout cipher$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("cipher"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const EVP_CIPHER *cipher
     * }
     */
    public static final AddressLayout cipher$layout() {
        return cipher$LAYOUT;
    }

    private static final long cipher$OFFSET = $LAYOUT.byteOffset(groupElement("cipher"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const EVP_CIPHER *cipher
     * }
     */
    public static final long cipher$offset() {
        return cipher$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const EVP_CIPHER *cipher
     * }
     */
    public static MemorySegment cipher(MemorySegment struct) {
        return struct.get(cipher$LAYOUT, cipher$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const EVP_CIPHER *cipher
     * }
     */
    public static void cipher(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(cipher$LAYOUT, cipher$OFFSET, fieldValue);
    }

    private static final SequenceLayout iv$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("iv"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char iv[16]
     * }
     */
    public static final SequenceLayout iv$layout() {
        return iv$LAYOUT;
    }

    private static final long iv$OFFSET = $LAYOUT.byteOffset(groupElement("iv"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char iv[16]
     * }
     */
    public static final long iv$offset() {
        return iv$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char iv[16]
     * }
     */
    public static MemorySegment iv(MemorySegment struct) {
        return struct.asSlice(iv$OFFSET, iv$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char iv[16]
     * }
     */
    public static void iv(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, iv$OFFSET, iv$LAYOUT.byteSize());
    }

    private static long[] iv$DIMS = { 16 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * unsigned char iv[16]
     * }
     */
    public static long[] iv$dimensions() {
        return iv$DIMS;
    }
    private static final VarHandle iv$ELEM_HANDLE = iv$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * unsigned char iv[16]
     * }
     */
    public static byte iv(MemorySegment struct, long index0) {
        return (byte)iv$ELEM_HANDLE.get(struct, iv$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * unsigned char iv[16]
     * }
     */
    public static void iv(MemorySegment struct, long index0, byte fieldValue) {
        iv$ELEM_HANDLE.set(struct, iv$OFFSET, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

