// Generated by jextract

package org.jquic.boringssl;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;

/**
 * {@snippet lang=c :
 * typedef struct evp_aead_ctx_st EVP_AEAD_CTX
 * }
 */
public class EVP_AEAD_CTX {
    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
            evp_h.C_POINTER.withName("aead"),
            evp_aead_ctx_st_state.layout().withName("state"),
            evp_h.C_CHAR.withName("tag_len"),
            MemoryLayout.paddingLayout(7)
    ).withName("evp_aead_ctx_st");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }
}

