// Generated by jextract

package org.jquic.boringssl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class evp_h extends evp_h_1 {

    evp_h() {
        // Should not be called directly
    }
    /**
     * {@snippet lang=c :
     * #define SN_dhSinglePass_cofactorDH_sha256kdf_scheme "dhSinglePass-cofactorDH-sha256kdf-scheme"
     * }
     */
    public static MemorySegment SN_dhSinglePass_cofactorDH_sha256kdf_scheme() {
        class Holder {
            static final MemorySegment SN_dhSinglePass_cofactorDH_sha256kdf_scheme
                = evp_h.LIBRARY_ARENA.allocateFrom("dhSinglePass-cofactorDH-sha256kdf-scheme");
        }
        return Holder.SN_dhSinglePass_cofactorDH_sha256kdf_scheme;
    }
    private static final int OBJ_dhSinglePass_cofactorDH_sha256kdf_scheme = (int)1L;
    /**
     * {@snippet lang=c :
     * #define OBJ_dhSinglePass_cofactorDH_sha256kdf_scheme 1
     * }
     */
    public static int OBJ_dhSinglePass_cofactorDH_sha256kdf_scheme() {
        return OBJ_dhSinglePass_cofactorDH_sha256kdf_scheme;
    }
    /**
     * {@snippet lang=c :
     * #define SN_dhSinglePass_cofactorDH_sha384kdf_scheme "dhSinglePass-cofactorDH-sha384kdf-scheme"
     * }
     */
    public static MemorySegment SN_dhSinglePass_cofactorDH_sha384kdf_scheme() {
        class Holder {
            static final MemorySegment SN_dhSinglePass_cofactorDH_sha384kdf_scheme
                = evp_h.LIBRARY_ARENA.allocateFrom("dhSinglePass-cofactorDH-sha384kdf-scheme");
        }
        return Holder.SN_dhSinglePass_cofactorDH_sha384kdf_scheme;
    }
    private static final int OBJ_dhSinglePass_cofactorDH_sha384kdf_scheme = (int)1L;
    /**
     * {@snippet lang=c :
     * #define OBJ_dhSinglePass_cofactorDH_sha384kdf_scheme 1
     * }
     */
    public static int OBJ_dhSinglePass_cofactorDH_sha384kdf_scheme() {
        return OBJ_dhSinglePass_cofactorDH_sha384kdf_scheme;
    }
    /**
     * {@snippet lang=c :
     * #define SN_dhSinglePass_cofactorDH_sha512kdf_scheme "dhSinglePass-cofactorDH-sha512kdf-scheme"
     * }
     */
    public static MemorySegment SN_dhSinglePass_cofactorDH_sha512kdf_scheme() {
        class Holder {
            static final MemorySegment SN_dhSinglePass_cofactorDH_sha512kdf_scheme
                = evp_h.LIBRARY_ARENA.allocateFrom("dhSinglePass-cofactorDH-sha512kdf-scheme");
        }
        return Holder.SN_dhSinglePass_cofactorDH_sha512kdf_scheme;
    }
    private static final int OBJ_dhSinglePass_cofactorDH_sha512kdf_scheme = (int)1L;
    /**
     * {@snippet lang=c :
     * #define OBJ_dhSinglePass_cofactorDH_sha512kdf_scheme 1
     * }
     */
    public static int OBJ_dhSinglePass_cofactorDH_sha512kdf_scheme() {
        return OBJ_dhSinglePass_cofactorDH_sha512kdf_scheme;
    }
    /**
     * {@snippet lang=c :
     * #define SN_dh_std_kdf "dh-std-kdf"
     * }
     */
    public static MemorySegment SN_dh_std_kdf() {
        class Holder {
            static final MemorySegment SN_dh_std_kdf
                = evp_h.LIBRARY_ARENA.allocateFrom("dh-std-kdf");
        }
        return Holder.SN_dh_std_kdf;
    }
    /**
     * {@snippet lang=c :
     * #define SN_dh_cofactor_kdf "dh-cofactor-kdf"
     * }
     */
    public static MemorySegment SN_dh_cofactor_kdf() {
        class Holder {
            static final MemorySegment SN_dh_cofactor_kdf
                = evp_h.LIBRARY_ARENA.allocateFrom("dh-cofactor-kdf");
        }
        return Holder.SN_dh_cofactor_kdf;
    }
    /**
     * {@snippet lang=c :
     * #define SN_X25519 "X25519"
     * }
     */
    public static MemorySegment SN_X25519() {
        class Holder {
            static final MemorySegment SN_X25519
                = evp_h.LIBRARY_ARENA.allocateFrom("X25519");
        }
        return Holder.SN_X25519;
    }
    private static final int OBJ_X25519 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define OBJ_X25519 1
     * }
     */
    public static int OBJ_X25519() {
        return OBJ_X25519;
    }
    /**
     * {@snippet lang=c :
     * #define SN_ED25519 "ED25519"
     * }
     */
    public static MemorySegment SN_ED25519() {
        class Holder {
            static final MemorySegment SN_ED25519
                = evp_h.LIBRARY_ARENA.allocateFrom("ED25519");
        }
        return Holder.SN_ED25519;
    }
    private static final int OBJ_ED25519 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define OBJ_ED25519 1
     * }
     */
    public static int OBJ_ED25519() {
        return OBJ_ED25519;
    }
    /**
     * {@snippet lang=c :
     * #define SN_chacha20_poly1305 "ChaCha20-Poly1305"
     * }
     */
    public static MemorySegment SN_chacha20_poly1305() {
        class Holder {
            static final MemorySegment SN_chacha20_poly1305
                = evp_h.LIBRARY_ARENA.allocateFrom("ChaCha20-Poly1305");
        }
        return Holder.SN_chacha20_poly1305;
    }
    /**
     * {@snippet lang=c :
     * #define LN_chacha20_poly1305 "chacha20-poly1305"
     * }
     */
    public static MemorySegment LN_chacha20_poly1305() {
        class Holder {
            static final MemorySegment LN_chacha20_poly1305
                = evp_h.LIBRARY_ARENA.allocateFrom("chacha20-poly1305");
        }
        return Holder.LN_chacha20_poly1305;
    }
    /**
     * {@snippet lang=c :
     * #define SN_kx_rsa "KxRSA"
     * }
     */
    public static MemorySegment SN_kx_rsa() {
        class Holder {
            static final MemorySegment SN_kx_rsa
                = evp_h.LIBRARY_ARENA.allocateFrom("KxRSA");
        }
        return Holder.SN_kx_rsa;
    }
    /**
     * {@snippet lang=c :
     * #define LN_kx_rsa "kx-rsa"
     * }
     */
    public static MemorySegment LN_kx_rsa() {
        class Holder {
            static final MemorySegment LN_kx_rsa
                = evp_h.LIBRARY_ARENA.allocateFrom("kx-rsa");
        }
        return Holder.LN_kx_rsa;
    }
    /**
     * {@snippet lang=c :
     * #define SN_kx_ecdhe "KxECDHE"
     * }
     */
    public static MemorySegment SN_kx_ecdhe() {
        class Holder {
            static final MemorySegment SN_kx_ecdhe
                = evp_h.LIBRARY_ARENA.allocateFrom("KxECDHE");
        }
        return Holder.SN_kx_ecdhe;
    }
    /**
     * {@snippet lang=c :
     * #define LN_kx_ecdhe "kx-ecdhe"
     * }
     */
    public static MemorySegment LN_kx_ecdhe() {
        class Holder {
            static final MemorySegment LN_kx_ecdhe
                = evp_h.LIBRARY_ARENA.allocateFrom("kx-ecdhe");
        }
        return Holder.LN_kx_ecdhe;
    }
    /**
     * {@snippet lang=c :
     * #define SN_kx_psk "KxPSK"
     * }
     */
    public static MemorySegment SN_kx_psk() {
        class Holder {
            static final MemorySegment SN_kx_psk
                = evp_h.LIBRARY_ARENA.allocateFrom("KxPSK");
        }
        return Holder.SN_kx_psk;
    }
    /**
     * {@snippet lang=c :
     * #define LN_kx_psk "kx-psk"
     * }
     */
    public static MemorySegment LN_kx_psk() {
        class Holder {
            static final MemorySegment LN_kx_psk
                = evp_h.LIBRARY_ARENA.allocateFrom("kx-psk");
        }
        return Holder.LN_kx_psk;
    }
    /**
     * {@snippet lang=c :
     * #define SN_auth_rsa "AuthRSA"
     * }
     */
    public static MemorySegment SN_auth_rsa() {
        class Holder {
            static final MemorySegment SN_auth_rsa
                = evp_h.LIBRARY_ARENA.allocateFrom("AuthRSA");
        }
        return Holder.SN_auth_rsa;
    }
    /**
     * {@snippet lang=c :
     * #define LN_auth_rsa "auth-rsa"
     * }
     */
    public static MemorySegment LN_auth_rsa() {
        class Holder {
            static final MemorySegment LN_auth_rsa
                = evp_h.LIBRARY_ARENA.allocateFrom("auth-rsa");
        }
        return Holder.LN_auth_rsa;
    }
    /**
     * {@snippet lang=c :
     * #define SN_auth_ecdsa "AuthECDSA"
     * }
     */
    public static MemorySegment SN_auth_ecdsa() {
        class Holder {
            static final MemorySegment SN_auth_ecdsa
                = evp_h.LIBRARY_ARENA.allocateFrom("AuthECDSA");
        }
        return Holder.SN_auth_ecdsa;
    }
    /**
     * {@snippet lang=c :
     * #define LN_auth_ecdsa "auth-ecdsa"
     * }
     */
    public static MemorySegment LN_auth_ecdsa() {
        class Holder {
            static final MemorySegment LN_auth_ecdsa
                = evp_h.LIBRARY_ARENA.allocateFrom("auth-ecdsa");
        }
        return Holder.LN_auth_ecdsa;
    }
    /**
     * {@snippet lang=c :
     * #define SN_auth_psk "AuthPSK"
     * }
     */
    public static MemorySegment SN_auth_psk() {
        class Holder {
            static final MemorySegment SN_auth_psk
                = evp_h.LIBRARY_ARENA.allocateFrom("AuthPSK");
        }
        return Holder.SN_auth_psk;
    }
    /**
     * {@snippet lang=c :
     * #define LN_auth_psk "auth-psk"
     * }
     */
    public static MemorySegment LN_auth_psk() {
        class Holder {
            static final MemorySegment LN_auth_psk
                = evp_h.LIBRARY_ARENA.allocateFrom("auth-psk");
        }
        return Holder.LN_auth_psk;
    }
    /**
     * {@snippet lang=c :
     * #define SN_kx_any "KxANY"
     * }
     */
    public static MemorySegment SN_kx_any() {
        class Holder {
            static final MemorySegment SN_kx_any
                = evp_h.LIBRARY_ARENA.allocateFrom("KxANY");
        }
        return Holder.SN_kx_any;
    }
    /**
     * {@snippet lang=c :
     * #define LN_kx_any "kx-any"
     * }
     */
    public static MemorySegment LN_kx_any() {
        class Holder {
            static final MemorySegment LN_kx_any
                = evp_h.LIBRARY_ARENA.allocateFrom("kx-any");
        }
        return Holder.LN_kx_any;
    }
    /**
     * {@snippet lang=c :
     * #define SN_auth_any "AuthANY"
     * }
     */
    public static MemorySegment SN_auth_any() {
        class Holder {
            static final MemorySegment SN_auth_any
                = evp_h.LIBRARY_ARENA.allocateFrom("AuthANY");
        }
        return Holder.SN_auth_any;
    }
    /**
     * {@snippet lang=c :
     * #define LN_auth_any "auth-any"
     * }
     */
    public static MemorySegment LN_auth_any() {
        class Holder {
            static final MemorySegment LN_auth_any
                = evp_h.LIBRARY_ARENA.allocateFrom("auth-any");
        }
        return Holder.LN_auth_any;
    }
    /**
     * {@snippet lang=c :
     * #define SN_ED448 "ED448"
     * }
     */
    public static MemorySegment SN_ED448() {
        class Holder {
            static final MemorySegment SN_ED448
                = evp_h.LIBRARY_ARENA.allocateFrom("ED448");
        }
        return Holder.SN_ED448;
    }
    private static final int OBJ_ED448 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define OBJ_ED448 1
     * }
     */
    public static int OBJ_ED448() {
        return OBJ_ED448;
    }
    /**
     * {@snippet lang=c :
     * #define SN_X448 "X448"
     * }
     */
    public static MemorySegment SN_X448() {
        class Holder {
            static final MemorySegment SN_X448
                = evp_h.LIBRARY_ARENA.allocateFrom("X448");
        }
        return Holder.SN_X448;
    }
    private static final int OBJ_X448 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define OBJ_X448 1
     * }
     */
    public static int OBJ_X448() {
        return OBJ_X448;
    }
    /**
     * {@snippet lang=c :
     * #define SN_sha512_256 "SHA512-256"
     * }
     */
    public static MemorySegment SN_sha512_256() {
        class Holder {
            static final MemorySegment SN_sha512_256
                = evp_h.LIBRARY_ARENA.allocateFrom("SHA512-256");
        }
        return Holder.SN_sha512_256;
    }
    /**
     * {@snippet lang=c :
     * #define LN_sha512_256 "sha512-256"
     * }
     */
    public static MemorySegment LN_sha512_256() {
        class Holder {
            static final MemorySegment LN_sha512_256
                = evp_h.LIBRARY_ARENA.allocateFrom("sha512-256");
        }
        return Holder.LN_sha512_256;
    }
    private static final int OBJ_sha512_256 = (int)2L;
    /**
     * {@snippet lang=c :
     * #define OBJ_sha512_256 2
     * }
     */
    public static int OBJ_sha512_256() {
        return OBJ_sha512_256;
    }
    /**
     * {@snippet lang=c :
     * #define SN_hkdf "HKDF"
     * }
     */
    public static MemorySegment SN_hkdf() {
        class Holder {
            static final MemorySegment SN_hkdf
                = evp_h.LIBRARY_ARENA.allocateFrom("HKDF");
        }
        return Holder.SN_hkdf;
    }
    /**
     * {@snippet lang=c :
     * #define LN_hkdf "hkdf"
     * }
     */
    public static MemorySegment LN_hkdf() {
        class Holder {
            static final MemorySegment LN_hkdf
                = evp_h.LIBRARY_ARENA.allocateFrom("hkdf");
        }
        return Holder.LN_hkdf;
    }
    /**
     * {@snippet lang=c :
     * #define SN_X25519Kyber768Draft00 "X25519Kyber768Draft00"
     * }
     */
    public static MemorySegment SN_X25519Kyber768Draft00() {
        class Holder {
            static final MemorySegment SN_X25519Kyber768Draft00
                = evp_h.LIBRARY_ARENA.allocateFrom("X25519Kyber768Draft00");
        }
        return Holder.SN_X25519Kyber768Draft00;
    }
    /**
     * {@snippet lang=c :
     * #define SN_X25519MLKEM768 "X25519MLKEM768"
     * }
     */
    public static MemorySegment SN_X25519MLKEM768() {
        class Holder {
            static final MemorySegment SN_X25519MLKEM768
                = evp_h.LIBRARY_ARENA.allocateFrom("X25519MLKEM768");
        }
        return Holder.SN_X25519MLKEM768;
    }
    private static final int EVP_PKEY_NONE = (int)0L;
    /**
     * {@snippet lang=c :
     * #define EVP_PKEY_NONE 0
     * }
     */
    public static int EVP_PKEY_NONE() {
        return EVP_PKEY_NONE;
    }
    private static final int EVP_PKEY_RSA = (int)6L;
    /**
     * {@snippet lang=c :
     * #define EVP_PKEY_RSA 6
     * }
     */
    public static int EVP_PKEY_RSA() {
        return EVP_PKEY_RSA;
    }
    private static final int EVP_PKEY_RSA_PSS = (int)912L;
    /**
     * {@snippet lang=c :
     * #define EVP_PKEY_RSA_PSS 912
     * }
     */
    public static int EVP_PKEY_RSA_PSS() {
        return EVP_PKEY_RSA_PSS;
    }
    private static final int EVP_PKEY_DSA = (int)116L;
    /**
     * {@snippet lang=c :
     * #define EVP_PKEY_DSA 116
     * }
     */
    public static int EVP_PKEY_DSA() {
        return EVP_PKEY_DSA;
    }
    private static final int EVP_PKEY_EC = (int)408L;
    /**
     * {@snippet lang=c :
     * #define EVP_PKEY_EC 408
     * }
     */
    public static int EVP_PKEY_EC() {
        return EVP_PKEY_EC;
    }
    private static final int EVP_PKEY_ED25519 = (int)949L;
    /**
     * {@snippet lang=c :
     * #define EVP_PKEY_ED25519 949
     * }
     */
    public static int EVP_PKEY_ED25519() {
        return EVP_PKEY_ED25519;
    }
    private static final int EVP_PKEY_X25519 = (int)948L;
    /**
     * {@snippet lang=c :
     * #define EVP_PKEY_X25519 948
     * }
     */
    public static int EVP_PKEY_X25519() {
        return EVP_PKEY_X25519;
    }
    private static final int EVP_PKEY_HKDF = (int)963L;
    /**
     * {@snippet lang=c :
     * #define EVP_PKEY_HKDF 963
     * }
     */
    public static int EVP_PKEY_HKDF() {
        return EVP_PKEY_HKDF;
    }
    private static final int EVP_PKEY_DH = (int)28L;
    /**
     * {@snippet lang=c :
     * #define EVP_PKEY_DH 28
     * }
     */
    public static int EVP_PKEY_DH() {
        return EVP_PKEY_DH;
    }
    private static final int EVP_PKEY_RSA2 = (int)19L;
    /**
     * {@snippet lang=c :
     * #define EVP_PKEY_RSA2 19
     * }
     */
    public static int EVP_PKEY_RSA2() {
        return EVP_PKEY_RSA2;
    }
    private static final int EVP_PKEY_X448 = (int)961L;
    /**
     * {@snippet lang=c :
     * #define EVP_PKEY_X448 961
     * }
     */
    public static int EVP_PKEY_X448() {
        return EVP_PKEY_X448;
    }
    private static final int EVP_PKEY_ED448 = (int)960L;
    /**
     * {@snippet lang=c :
     * #define EVP_PKEY_ED448 960
     * }
     */
    public static int EVP_PKEY_ED448() {
        return EVP_PKEY_ED448;
    }
}

