/*
 * Copyright 2026 Fedor Malyshev
 *
 * Licensed under the Apache License, Version 2.0 (the "License") ;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by jextract

package org.jquic.boringssl;

import java.lang.foreign.*;

/**
 * {@snippet lang=c :
 * union evp_aead_ctx_st_state {
 *     uint8_t opaque[560];
 *     uint64_t alignment;
 * }
 * }
 */
public class evp_aead_ctx_st_state {

    private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
        MemoryLayout.sequenceLayout(560, evp_h.C_CHAR).withName("opaque"),
        evp_h.C_LONG_LONG.withName("alignment")
    ).withName("evp_aead_ctx_st_state");

    /**
     * The layout of this union
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

}

