// Generated by jextract

package org.jquic.boringssl;

import java.lang.foreign.*;

/**
 * {@snippet lang=c :
 * union evp_aead_ctx_st_state {
 *     uint8_t opaque[560];
 *     uint64_t alignment;
 * }
 * }
 */
public class evp_aead_ctx_st_state {

    private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
        MemoryLayout.sequenceLayout(560, evp_h.C_CHAR).withName("opaque"),
        evp_h.C_LONG_LONG.withName("alignment")
    ).withName("evp_aead_ctx_st_state");

    /**
     * The layout of this union
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

}

