// Generated by jextract

package org.jquic.boringssl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct hmac_ctx_st {
 *     const EVP_MD *md;
 *     EVP_MD_CTX md_ctx;
 *     EVP_MD_CTX i_ctx;
 *     EVP_MD_CTX o_ctx;
 * }
 * }
 */
public class hmac_ctx_st {

    hmac_ctx_st() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        hmac_h.C_POINTER.withName("md"),
        env_md_ctx_st.layout().withName("md_ctx"),
        env_md_ctx_st.layout().withName("i_ctx"),
        env_md_ctx_st.layout().withName("o_ctx")
    ).withName("hmac_ctx_st");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout md$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("md"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const EVP_MD *md
     * }
     */
    public static final AddressLayout md$layout() {
        return md$LAYOUT;
    }

    private static final long md$OFFSET = $LAYOUT.byteOffset(groupElement("md"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const EVP_MD *md
     * }
     */
    public static final long md$offset() {
        return md$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const EVP_MD *md
     * }
     */
    public static MemorySegment md(MemorySegment struct) {
        return struct.get(md$LAYOUT, md$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const EVP_MD *md
     * }
     */
    public static void md(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(md$LAYOUT, md$OFFSET, fieldValue);
    }

    private static final GroupLayout md_ctx$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("md_ctx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * EVP_MD_CTX md_ctx
     * }
     */
    public static final GroupLayout md_ctx$layout() {
        return md_ctx$LAYOUT;
    }

    private static final long md_ctx$OFFSET = $LAYOUT.byteOffset(groupElement("md_ctx"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * EVP_MD_CTX md_ctx
     * }
     */
    public static final long md_ctx$offset() {
        return md_ctx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * EVP_MD_CTX md_ctx
     * }
     */
    public static MemorySegment md_ctx(MemorySegment struct) {
        return struct.asSlice(md_ctx$OFFSET, md_ctx$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * EVP_MD_CTX md_ctx
     * }
     */
    public static void md_ctx(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, md_ctx$OFFSET, md_ctx$LAYOUT.byteSize());
    }

    private static final GroupLayout i_ctx$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("i_ctx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * EVP_MD_CTX i_ctx
     * }
     */
    public static final GroupLayout i_ctx$layout() {
        return i_ctx$LAYOUT;
    }

    private static final long i_ctx$OFFSET = $LAYOUT.byteOffset(groupElement("i_ctx"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * EVP_MD_CTX i_ctx
     * }
     */
    public static final long i_ctx$offset() {
        return i_ctx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * EVP_MD_CTX i_ctx
     * }
     */
    public static MemorySegment i_ctx(MemorySegment struct) {
        return struct.asSlice(i_ctx$OFFSET, i_ctx$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * EVP_MD_CTX i_ctx
     * }
     */
    public static void i_ctx(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, i_ctx$OFFSET, i_ctx$LAYOUT.byteSize());
    }

    private static final GroupLayout o_ctx$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("o_ctx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * EVP_MD_CTX o_ctx
     * }
     */
    public static final GroupLayout o_ctx$layout() {
        return o_ctx$LAYOUT;
    }

    private static final long o_ctx$OFFSET = $LAYOUT.byteOffset(groupElement("o_ctx"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * EVP_MD_CTX o_ctx
     * }
     */
    public static final long o_ctx$offset() {
        return o_ctx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * EVP_MD_CTX o_ctx
     * }
     */
    public static MemorySegment o_ctx(MemorySegment struct) {
        return struct.asSlice(o_ctx$OFFSET, o_ctx$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * EVP_MD_CTX o_ctx
     * }
     */
    public static void o_ctx(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, o_ctx$OFFSET, o_ctx$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

